import React, { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    // Home page
    smartBilling: 'GrociBill',
    tagline: 'Voice-Enabled Billing and Product Management for Your Shop',
    voiceToText: 'Voice to Text',
    pinVoiceAuth: 'PIN Login',
    dailySecurityCodes: 'Voice Enabled',
    newShop: 'New Shop?',
    newShopDesc: 'Register your shop and become the main shopkeeper in 2 simple steps',
    registerShop: 'Register Shop',
    alreadyRegistered: 'Already Registered?',
    alreadyRegisteredDesc: 'Login with your Shop ID and 4-digit PIN',
    login: 'Login',

    // How It Works
    howItWorks: 'How It Works',
    step1Title: 'Register Shop',
    step1Desc: 'Create your shop account and set a secure PIN',
    step2Title: 'Login with PIN',
    step2Desc: 'Login securely using Shop ID, role, and PIN',
    step3Title: 'Use Voice Commands',
    step3Desc: 'Tap mic and speak item name and price',
    step4Title: 'Auto Bill Generation',
    step4Desc: 'Items are added and bill is created instantly',
    step5Title: 'Share / Print',
    step5Desc: 'Send bill via WhatsApp or print',

    // Key Features
    keyFeatures: 'Key Features',
    feature1Title: 'Voice Billing',
    feature1Desc: 'Speak product name and create bill instantly',
    feature2Title: 'Voice Price Update',
    feature2Desc: 'Update prices using voice — no manual work',
    feature3Title: 'Secure Access',
    feature3Desc: 'Only registered shopkeepers can do billing',
    feature4Title: 'Fast Billing',
    feature4Desc: 'Generate bills quickly with simple voice input',
    feature5Title: 'Clean Bills',
    feature5Desc: 'Get clear and neat bills for customers',
    feature6Title: 'Add Products by Voice',
    feature6Desc: 'Easily add new items using voice',
    feature7Title: 'Smart Reports',
    feature7Desc: 'View daily, weekly, monthly and item-wise reports',
    feature8Title: 'Low Stock Alerts',
    feature8Desc: 'Get alerts when products are running low',

    // Login page
    welcomeBack: 'Welcome Back!',
    enterShopId: 'Enter your Shop ID to login',
    shopId: 'Shop ID',
    pasteShopId: 'Paste your Shop ID here',
    continue: 'Continue',
    checking: 'Checking...',
    shopNotFound: 'Shop not found. Please check your Shop ID.',
    selectRole: 'Select Your Role',
    whoAreYou: 'Who are you?',
    mainShopkeeper: 'Main Shopkeeper',
    fullAccess: 'Full access to all features',
    alternativeShopkeeper: 'Alternative Shopkeeper',
    billingAccessOnly: 'Same access as main shopkeeper',
    back: 'Back',
    enterPin: 'Enter your 4-digit PIN',
    verifying: 'Verifying...',
    wrongPin: 'Wrong PIN. Please try again.',
    newHere: 'New here?',
    registerAShop: 'Register a shop',
    backToHome: 'Back to Home',

    // Register page
    registerYourShop: 'Register Your Shop',
    createNewShop: 'Create a new shop and become the main shopkeeper',
    shopName: 'Shop Name',
    shopNamePlaceholder: 'e.g., Kumar Grocery Store',
    yourName: 'Your Name',
    yourNamePlaceholder: 'e.g., Ravi Kumar',
    location: 'Location',
    locationPlaceholder: 'e.g., Chennai, Tamil Nadu',
    nextSetPin: 'Next: Set Your PIN',
    setYourPin: 'Set Your PIN',
    createPinFor: 'Create a 4-digit PIN for',
    creatingShop: 'Creating your shop...',
    backToDetails: 'Back to details',
    shopCreated: 'Shop Created!',
    shopReady: 'Your shop is ready. Save your Shop ID:',
    yourShopId: 'Your Shop ID',
    copied: 'Copied!',
    important: 'Important!',
    saveShopId: 'Save this Shop ID! You\'ll need it to login and to add alternative shopkeepers.',
    goToDashboard: 'Go to Dashboard',
    alreadyHaveShop: 'Already have a shop?',
    signIn: 'Sign in',

    // Dashboard
    dashboard: 'Dashboard',
    welcomeBackName: 'Welcome back,',
    accountInfo: 'Account Info',
    shopIdLabel: 'Shop ID',
    shopNameLabel: 'Shop Name',
    roleLabel: 'Role',
    manageProducts: 'Manage Products',
    manageProductsDesc: 'Add, edit, or remove products from your inventory',
    goToProducts: 'Go to Products',
    createBill: 'Create Bill',
    createBillDesc: 'Create a new bill quickly with voice or manual selection',
    newBill: 'New Bill',
    viewAllBills: 'View All Bills',
    viewBillsDesc: 'View history of all bills created',
    viewBills: 'View Bills',
    reports: 'Reports',
    reportsDesc: 'Track daily, monthly, and yearly performance',
    viewReports: 'View Reports',
    addAlternativeShopkeeper: 'Add Alternative Shopkeeper',
    addAltShopkeeperDesc: 'Add another shopkeeper with full access',
    addShopkeeper: 'Add Shopkeeper',

    // Navbar
    products: 'Products',
    billing: 'Billing',
    refresh: 'Refresh',
    logout: 'Logout',

    // Billing page
    voiceBilling: 'Voice Billing',
    stopVoice: 'Stop Voice',
    listening: 'Listening... Say product names!',
    sayProductNames: 'Say product names like "Rice", "Sugar", "Amul Butter"',
    added: 'Added',
    productsLabel: 'Products',
    searchProducts: 'Search products...',
    noProducts: 'No products available. Add products first.',
    noMatchingProducts: 'No matching products found.',
    billSummary: 'Bill Summary',
    noItemsAdded: 'No items added yet',
    clickOrVoice: 'Click products or use voice to add',
    items: 'Items',
    total: 'Total',
    processing: 'Processing...',
    createBillBtn: 'Create Bill',
    cancel: 'Cancel',

    // Bills page
    allBills: 'All Bills',
    loadingBills: 'Loading bills...',
    noBillsCreated: 'No bills created yet',
    billNumber: 'Bill #',
    date: 'Date',
    shopkeeper: 'Shopkeeper',

    // Language toggle
    english: 'English',
    tamil: 'தமிழ்',

    // Common labels
    currency: 'Rs.',
    each: 'each',
    item: 'Item',
    removed: 'Removed',
    billCleared: 'Bill cleared',
    billNeedsItem: 'Bill must have at least one item',
    billCreateFailed: 'Failed to create bill',
    billCreatedSuccess: 'Bill created successfully!',
    billsFetchFailed: 'Failed to fetch bills: {{message}}',
    billFrom: 'Bill from',
    thankYou: 'Thank you for your purchase!',
    poweredBy: 'Powered by GrociBill',
    onlyStockLeft: 'Only {{available}} left in stock for {{product}}',
    failedToFetchProducts: 'Failed to fetch products',
    confirmDelete: 'Are you sure?',
    deleteProductFailed: 'Failed to delete product',
    productUpdated: '✓ Updated {{name}}',
    saveProductFailed: 'Failed to save product',
    voiceNeedPriceQuantity: 'Product "{{name}}" - please say quantity and price.',
    voicePriceUpdateSeparate: 'Price update for "{{name}}" is available in the Price Update module.',
    voiceNeedQuantityExisting: 'Say quantity to add stock for "{{name}}".',
    voiceQuantityAdded: '✓ Added {{qty}} qty to {{name}} (Total: {{total}})',
    voiceQuantityAddedPriceIgnored: '✓ Added {{qty}} qty to {{name}} (price update ignored)',
    voiceProductAdded: '✓ Added {{name}} (Qty: {{qty}}, Price: Rs.{{price}})',
    noShopkeeperFound: 'No {{role}} shopkeeper found for this shop.',
    hiName: 'Hi, {{name}}!',
    mobileVoiceHint: 'Mobile: tap the mic each time (push-to-talk).',
    micAccessDenied: 'Microphone access denied. Please allow microphone permissions.',
    micBusy: 'Microphone busy. Stop other recordings and try again.',
    speechError: 'Speech error',
    voiceStartFailed: 'Failed to start',
    useChrome: 'Use Chrome or Edge browser.',
    voiceRestartStopped: 'Voice stopped due to unstable microphone on mobile. Tap Voice Billing again.',
    voiceHeard: 'Heard: "{{text}}"',
    productNotFound: 'Product not found: "{{segment}}"',
    lowStockAlertTitle: 'Low stock alert',
    lowStockAlertItem: '{{name}} ({{qty}})',
    lowStockInline: 'Low stock: {{qty}}',
    expiryAlertTitle: 'Expiry alert ({{days}} days)',
    expiredLabel: 'Expired',
    expiringSoonLabel: 'Expiring soon',
    expiringItem: '{{name}} ({{days}} days)',
    expiringInDays: 'Expiring in {{days}} days',
    voiceUnsupported: 'Voice capture not supported on this device.',
    voiceRecording: 'Recording...',
    voiceMatchSuccess: 'Voice verified successfully.',
    voiceMatchFail: 'Voice did not match. Please try again.',
    voiceEnrollSuccess: 'Voice enrolled successfully.',
    voiceEnrollFail: 'Failed to enroll voice. Please try again.',
    voiceNoClear: 'No clear voice detected. Please try again in a quiet place.',
    voiceVerifyTitle: 'Voice Verification',
    voiceVerifyDesc: 'Speak a short phrase to verify your voice.',
    voiceEnrollTitle: 'Voice Enrollment',
    voiceEnrollDesc: 'Speak the daily code to register your voice (required every login).',
    voicePrompt: 'Tap mic and speak for 2-3 seconds.',
    voiceDailyCodeLabel: 'Today\'s voice code',
    voiceDailyCodeHint: 'Speak this code clearly while recording.',
    voiceScore: 'Match score: {{score}}',
    voiceStart: 'Start Voice',
    voiceSkip: 'Skip',
    voiceSaving: 'Saving voice...',
    voiceVerifyRequired: 'Voice verification is required to continue.',
    addProduct: 'Add Product',
    editProductTitle: 'Edit Product',
    addNewProduct: 'Add New Product',
    addProductByVoice: 'Add Product by Voice',
    voiceAddHintAdd: 'Add: "Tomato 10kg 50rs"',
    voiceAddHintQuantity: 'Quantity update: "Tomato 20kg" (adds to stock)',
    voiceAddHintPrice: 'Price update: use Price Update module',
    startSpeaking: 'Start Speaking',
    stopListening: 'Stop Listening',
    youSaid: 'You said:',
    productNameLabel: 'Product Name',
    productNamePlaceholder: 'Product name',
    brandLabel: 'Brand',
    brandPlaceholder: 'Brand name (optional)',
    priceLabel: 'Price (Rs.)',
    quantityLabel: 'Quantity',
    expiryDateLabel: 'Expiry Date',
    expiryDateHelp: 'Set expiry date for alerts (optional)',
    expiryDateValue: 'Expiry date: {{date}}',
    synonymsLabel: 'Synonyms / Alternative Names',
    synonymsPlaceholder: 'e.g., curd, dahi, yogurt (comma separated)',
    synonymsHelp: 'Add alternative names so it can be found when spoken differently',
    saving: 'Saving...',
    updateProduct: 'Update Product',
    edit: 'Edit',
    delete: 'Delete',
    reportsLoadFailed: 'Failed to load reports',
    reportsTitle: 'Sales Reports',
    reportsSubtitle: 'Track shop performance by day, month, and year.',
    breakdownByPeriod: 'Breakdown by {{period}}',
    periodLabel: 'Period',
    salesLabel: 'Sales',
    billsLabel: 'Bills',
    itemsSoldLabel: 'Items Sold',
    avgBillLabel: 'Avg Bill',
    noReportData: 'No bill data available for this period.',
    productReportTitle: 'Product Sales',
    productReportSubtitle: 'Track sales for a specific product.',
    selectProduct: 'Select product',
    loadingProductReport: 'Loading product report...',
    loadingReports: 'Loading reports...',
    selectProductHint: 'Choose a product to see its sales.',
    totalSales: 'Total Sales',
    avgPriceLabel: 'Avg Price',
    daily: 'Daily',
    monthly: 'Monthly',
    yearly: 'Yearly',
    priceUpdate: 'Price Update',
    priceUpdateDesc: 'Update product prices by voice.',
    priceUpdateAction: 'Update Price',
    priceUpdateTitle: 'Voice Price Update',
    priceUpdateVoiceTitle: 'Update Price by Voice',
    priceUpdateHint: 'Say "Rice price 50" or "Update sugar price to 42".',
    priceUpdateNotDetected: 'No valid price update detected.',
    priceUpdateInvalid: 'Invalid price detected.',
    priceUpdateDetected: 'Detected: {{name}} → Rs.{{price}}',
    priceUpdateFailed: 'Failed to update price.',
    priceUpdatedSuccess: '✓ Updated {{name}} price to Rs.{{price}}',
    priceUpdateDetectedTitle: 'Confirm price update',
    currentPriceLabel: 'Current price',
    applyPriceUpdate: 'Apply Update',
    pinHint: 'Enter 4-digit PIN',
    enterShopIdError: 'Please enter your Shop ID',
    fillAllFields: 'Please fill all fields',
    fillRequiredFields: 'Please fill all required fields',
    registerShopFailed: 'Failed to register shop',
    registerShopkeeperFailed: 'Failed to register shopkeeper',
    registering: 'Registering...',
    selectYourName: 'Select Your Name',
    multipleShopkeepersFound: 'Multiple shopkeepers found. Please select your name.',
    print: 'Print',
    shareViaWhatsapp: 'Share via WhatsApp'
  },
  ta: {
    // Home page
    smartBilling: 'GrociBill',
    tagline: 'உங்கள் கடைக்கான குரல்-இயக்கப்பட்ட பில்லிங் மற்றும் பொருள் மேலாண்மை',
    voiceToText: 'குரல் உரையாக',
    pinVoiceAuth: 'PIN உள்நுழைவு',
    dailySecurityCodes: 'குரல் இயக்கப்பட்டது',
    newShop: 'புதிய கடையா?',
    newShopDesc: '2 எளிய படிகளில் உங்கள் கடையை பதிவு செய்து முதன்மை கடைக்காரராக மாறுங்கள்',
    registerShop: 'கடை பதிவு',
    alreadyRegistered: 'ஏற்கனவே பதிவு செய்துள்ளீர்களா?',
    alreadyRegisteredDesc: 'உங்கள் கடை ID மற்றும் 4-இலக்க PIN உடன் உள்நுழையவும்',
    login: 'உள்நுழை',

    // How It Works
    howItWorks: 'இது எப்படி வேலை செய்கிறது',
    step1Title: 'கடை பதிவு',
    step1Desc: 'உங்கள் கடை கணக்கை உருவாக்கி பாதுகாப்பான PIN அமைக்கவும்',
    step2Title: 'PIN மூலம் உள்நுழை',
    step2Desc: 'கடை ID, பங்கு மற்றும் PIN மூலம் பாதுகாப்பாக உள்நுழையவும்',
    step3Title: 'குரல் கட்டளைகளை பயன்படுத்து',
    step3Desc: 'மைக்கை தட்டி பொருள் பெயர் மற்றும் விலையை பேசுங்கள்',
    step4Title: 'தானியங்கி பில் உருவாக்கம்',
    step4Desc: 'பொருட்கள் சேர்க்கப்பட்டு பில் உடனடியாக உருவாக்கப்படும்',
    step5Title: 'பகிர் / அச்சிடு',
    step5Desc: 'WhatsApp வழியாக பில் அனுப்பு அல்லது அச்சிடு',

    // Key Features
    keyFeatures: 'முக்கிய அம்சங்கள்',
    feature1Title: 'குரல் பில்லிங்',
    feature1Desc: 'பொருள் பெயரை பேசி உடனடியாக பில் உருவாக்கு',
    feature2Title: 'குரல் விலை புதுப்பிப்பு',
    feature2Desc: 'குரல் பயன்படுத்தி விலைகளை புதுப்பிக்கவும் — கைமுறை வேலை இல்லை',
    feature3Title: 'பாதுகாப்பான அணுகல்',
    feature3Desc: 'பதிவுசெய்த கடைக்காரர்கள் மட்டுமே பில்லிங் செய்ய முடியும்',
    feature4Title: 'வேகமான பில்லிங்',
    feature4Desc: 'எளிய குரல் உள்ளீட்டுடன் விரைவாக பில்கள் உருவாக்கு',
    feature5Title: 'தெளிவான பில்கள்',
    feature5Desc: 'வாடிக்கையாளர்களுக்கு தெளிவான மற்றும் சுத்தமான பில்கள் பெறுங்கள்',
    feature6Title: 'குரல் மூலம் பொருட்கள் சேர்',
    feature6Desc: 'குரல் பயன்படுத்தி எளிதாக புதிய பொருட்களை சேர்க்கவும்',
    feature7Title: 'ஸ்மார்ட் அறிக்கைகள்',
    feature7Desc: 'தினசரி, வாராந்திர, மாதாந்திர மற்றும் பொருள்வாரியான அறிக்கைகளைப் பார்க்கவும்',
    feature8Title: 'குறைந்த கையிருப்பு எச்சரிக்கைகள்',
    feature8Desc: 'பொருட்கள் குறைவாக இருக்கும்போது எச்சரிக்கைகள் பெறுங்கள்',

    // Login page
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்!',
    enterShopId: 'உள்நுழைய உங்கள் கடை ID ஐ உள்ளிடவும்',
    shopId: 'கடை ID',
    pasteShopId: 'உங்கள் கடை ID ஐ இங்கே ஒட்டவும்',
    continue: 'தொடர்க',
    checking: 'சரிபார்க்கிறது...',
    shopNotFound: 'கடை கிடைக்கவில்லை. உங்கள் கடை ID ஐ சரிபார்க்கவும்.',
    selectRole: 'உங்கள் பங்கை தேர்வு செய்யவும்',
    whoAreYou: 'நீங்கள் யார்?',
    mainShopkeeper: 'முதன்மை கடைக்காரர்',
    fullAccess: 'அனைத்து அம்சங்களுக்கும் முழு அணுகல்',
    alternativeShopkeeper: 'மாற்று கடைக்காரர்',
    billingAccessOnly: 'முதன்மை கடைக்காரருக்கு சமமான அணுகல்',
    back: 'பின்செல்',
    enterPin: 'உங்கள் 4-இலக்க PIN ஐ உள்ளிடவும்',
    verifying: 'சரிபார்க்கிறது...',
    wrongPin: 'தவறான PIN. மீண்டும் முயற்சிக்கவும்.',
    newHere: 'புதியவரா?',
    registerAShop: 'கடையை பதிவு செய்யவும்',
    backToHome: 'முகப்புக்கு திரும்பு',

    // Register page
    registerYourShop: 'உங்கள் கடையை பதிவு செய்யவும்',
    createNewShop: 'புதிய கடையை உருவாக்கி முதன்மை கடைக்காரராக மாறுங்கள்',
    shopName: 'கடை பெயர்',
    shopNamePlaceholder: 'எ.கா., குமார் மளிகை கடை',
    yourName: 'உங்கள் பெயர்',
    yourNamePlaceholder: 'எ.கா., ரவி குமார்',
    location: 'இடம்',
    locationPlaceholder: 'எ.கா., சென்னை, தமிழ்நாடு',
    nextSetPin: 'அடுத்து: உங்கள் PIN அமைக்கவும்',
    setYourPin: 'உங்கள் PIN அமைக்கவும்',
    createPinFor: '4-இலக்க PIN உருவாக்கவும்',
    creatingShop: 'உங்கள் கடையை உருவாக்குகிறது...',
    backToDetails: 'விவரங்களுக்கு திரும்பு',
    shopCreated: 'கடை உருவாக்கப்பட்டது!',
    shopReady: 'உங்கள் கடை தயார். உங்கள் கடை ID ஐ சேமிக்கவும்:',
    yourShopId: 'உங்கள் கடை ID',
    copied: 'நகலெடுக்கப்பட்டது!',
    important: 'முக்கியம்!',
    saveShopId: 'இந்த கடை ID ஐ சேமிக்கவும்! உள்நுழைவதற்கும் மாற்று கடைக்காரர்களை சேர்ப்பதற்கும் இது தேவை.',
    goToDashboard: 'டாஷ்போர்டுக்கு செல்',
    alreadyHaveShop: 'ஏற்கனவே கடை உள்ளதா?',
    signIn: 'உள்நுழை',

    // Dashboard
    dashboard: 'டாஷ்போர்டு',
    welcomeBackName: 'மீண்டும் வரவேற்கிறோம்,',
    accountInfo: 'கணக்கு தகவல்',
    shopIdLabel: 'கடை ID',
    shopNameLabel: 'கடை பெயர்',
    roleLabel: 'பங்கு',
    manageProducts: 'பொருட்களை நிர்வகி',
    manageProductsDesc: 'உங்கள் சரக்கிலிருந்து பொருட்களை சேர்க்கவும், திருத்தவும் அல்லது அகற்றவும்',
    goToProducts: 'பொருட்களுக்கு செல்',
    createBill: 'பில் உருவாக்கு',
    createBillDesc: 'குரல் அல்லது கையேடு மூலம் விரைவாக புதிய பில் உருவாக்கு',
    newBill: 'புதிய பில்',
    viewAllBills: 'அனைத்து பில்களையும் பார்',
    viewBillsDesc: 'உருவாக்கப்பட்ட அனைத்து பில்களின் வரலாற்றைப் பார்க்கவும்',
    viewBills: 'பில்களைப் பார்',
    reports: 'அறிக்கைகள்',
    reportsDesc: 'தினசரி, மாதாந்திர, வருடாந்திர செயல்திறனை கண்காணிக்கவும்',
    viewReports: 'அறிக்கைகளைப் பார்',
    addAlternativeShopkeeper: 'மாற்று கடைக்காரர் சேர்',
    addAltShopkeeperDesc: 'முழு அணுகலுடன் மற்றொரு கடைக்காரரை சேர்க்கவும்',
    addShopkeeper: 'கடைக்காரர் சேர்',

    // Navbar
    products: 'பொருட்கள்',
    billing: 'பில்லிங்',
    refresh: 'புதுப்பிக்கவும்',
    logout: 'வெளியேறு',

    // Billing page
    voiceBilling: 'குரல் பில்லிங்',
    stopVoice: 'குரலை நிறுத்து',
    listening: 'கேட்கிறது... பொருள் பெயர்களை சொல்லுங்கள்!',
    sayProductNames: '"அரிசி", "சர்க்கரை" போன்ற பொருள் பெயர்களை சொல்லுங்கள்',
    added: 'சேர்க்கப்பட்டது',
    productsLabel: 'பொருட்கள்',
    searchProducts: 'பொருட்களைத் தேடு...',
    noProducts: 'பொருட்கள் இல்லை. முதலில் பொருட்களைச் சேர்க்கவும்.',
    noMatchingProducts: 'பொருந்தும் பொருட்கள் இல்லை.',
    billSummary: 'பில் சுருக்கம்',
    noItemsAdded: 'இன்னும் பொருட்கள் சேர்க்கப்படவில்லை',
    clickOrVoice: 'சேர்க்க பொருட்களை கிளிக் செய்யவும் அல்லது குரலைப் பயன்படுத்தவும்',
    items: 'பொருட்கள்',
    total: 'மொத்தம்',
    processing: 'செயலாக்குகிறது...',
    createBillBtn: 'பில் உருவாக்கு',
    cancel: 'ரத்து செய்',

    // Bills page
    allBills: 'அனைத்து பில்கள்',
    loadingBills: 'பில்களை ஏற்றுகிறது...',
    noBillsCreated: 'இன்னும் பில்கள் உருவாக்கப்படவில்லை',
    billNumber: 'பில் #',
    date: 'தேதி',
    shopkeeper: 'கடைக்காரர்',

    // Language toggle
    english: 'English',
    tamil: 'தமிழ்',

    // Common labels
    currency: 'ரூ.',
    each: 'ஒவ்வொன்றுக்கு',
    item: 'பொருள்',
    removed: 'நீக்கப்பட்டது',
    billCleared: 'பில் காலி செய்யப்பட்டது',
    billNeedsItem: 'பிலில் குறைந்தது ஒரு பொருள் இருக்க வேண்டும்',
    billCreateFailed: 'பில் உருவாக்க முடியவில்லை',
    billCreatedSuccess: 'பில் வெற்றிகரமாக உருவாக்கப்பட்டது!',
    billsFetchFailed: 'பில்களை பெற முடியவில்லை: {{message}}',
    billFrom: 'பில் -',
    thankYou: 'வருகைக்கு நன்றி!',
    poweredBy: 'GrociBill மூலம் இயக்கப்படுகிறது',
    onlyStockLeft: '{{product}} க்கு {{available}} மட்டுமே உள்ளது',
    failedToFetchProducts: 'பொருட்களை பெற முடியவில்லை',
    confirmDelete: 'நீங்கள் உறுதியாக உள்ளீர்களா?',
    deleteProductFailed: 'பொருளை நீக்க முடியவில்லை',
    productUpdated: '✓ {{name}} புதுப்பிக்கப்பட்டது',
    saveProductFailed: 'பொருளை சேமிக்க முடியவில்லை',
    voiceNeedPriceQuantity: '"{{name}}" - அளவும் விலையும் சொல்லுங்கள்.',
    voicePriceUpdateSeparate: '"{{name}}" விலை மாற்றம் - விலை புதுப்பிப்பு பகுதியில் செய்யுங்கள்.',
    voiceNeedQuantityExisting: '"{{name}}" க்கு அளவை சொல்லுங்கள்.',
    voiceQuantityAdded: '✓ {{name}} க்கு {{qty}} சேர்க்கப்பட்டது (மொத்தம்: {{total}})',
    voiceQuantityAddedPriceIgnored: '✓ {{name}} க்கு {{qty}} சேர்க்கப்பட்டது (விலை மாற்றம் கவனிக்கப்படவில்லை)',
    voiceProductAdded: '✓ {{name}} சேர்க்கப்பட்டது (அளவு: {{qty}}, விலை: ரூ.{{price}})',
    noShopkeeperFound: 'இந்த கடைக்கு {{role}} கிடைக்கவில்லை.',
    hiName: 'வணக்கம், {{name}}!',
    mobileVoiceHint: 'மொபைல்: ஒவ்வொரு முறையும் மைக் தட்டவும் (புஷ்-டூ-டாக்).',
    micAccessDenied: 'மைக்ரோஃபோன் அனுமதி இல்லை. அனுமதியை வழங்கவும்.',
    micBusy: 'மைக்ரோஃபோன் பயன்படுத்தப்படுகிறது. மற்ற பதிவுகளை நிறுத்தி மீண்டும் முயற்சிக்கவும்.',
    speechError: 'குரல் பிழை',
    voiceStartFailed: 'தொடங்க முடியவில்லை',
    useChrome: 'Chrome அல்லது Edge பயன்படுத்தவும்.',
    voiceRestartStopped: 'மொபைலில் மைக்ரோஃபோன் நிலையற்றதால் குரல் நிறுத்தப்பட்டது. மீண்டும் தொடங்குங்கள்.',
    voiceHeard: 'கேட்டது: "{{text}}"',
    productNotFound: 'பொருள் கிடைக்கவில்லை: "{{segment}}"',
    lowStockAlertTitle: 'குறைந்த கையிருப்பு எச்சரிக்கை',
    lowStockAlertItem: '{{name}} ({{qty}})',
    lowStockInline: 'குறைந்த கையிருப்பு: {{qty}}',
    expiryAlertTitle: 'காலாவதி எச்சரிக்கை ({{days}} நாட்கள்)',
    expiredLabel: 'காலாவதி',
    expiringSoonLabel: 'விரைவில் காலாவதி',
    expiringItem: '{{name}} ({{days}} நாட்கள்)',
    expiringInDays: '{{days}} நாட்களில் காலாவதி',
    voiceUnsupported: 'இந்த சாதனத்தில் குரல் பதிவு ஆதரவு இல்லை.',
    voiceRecording: 'பதிவு நடக்கிறது...',
    voiceMatchSuccess: 'குரல் சரிபார்ப்பு வெற்றி.',
    voiceMatchFail: 'குரல் பொருந்தவில்லை. மீண்டும் முயற்சிக்கவும்.',
    voiceEnrollSuccess: 'குரல் பதிவுசெய்யப்பட்டது.',
    voiceEnrollFail: 'குரல் பதிவு தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    voiceNoClear: 'குரல் தெளிவாக இல்லை. அமைதியான இடத்தில் மீண்டும் முயற்சிக்கவும்.',
    voiceVerifyTitle: 'குரல் சரிபார்ப்பு',
    voiceVerifyDesc: 'உங்கள் குரலை சரிபார்க்க ஒரு குறுகிய வாக்கியம் சொல்லுங்கள்.',
    voiceEnrollTitle: 'குரல் பதிவு',
    voiceEnrollDesc: 'இன்றைய குறியீட்டை சொல்லி குரல் பதிவு செய்யுங்கள் (ஒவ்வொரு உள்நுழைவிலும்).',
    voicePrompt: 'மைக் தட்டி 2-3 விநாடிகள் பேசுங்கள்.',
    voiceDailyCodeLabel: 'இன்றைய குரல் குறியீடு',
    voiceDailyCodeHint: 'பதிவு செய்யும் போது இந்தக் குறியீட்டை தெளிவாக சொல்லுங்கள்.',
    voiceScore: 'பொருந்தும் மதிப்பு: {{score}}',
    voiceStart: 'குரல் தொடக்கு',
    voiceSkip: 'தவிர்',
    voiceSaving: 'குரல் சேமிக்கிறது...',
    voiceVerifyRequired: 'தொடர குரல் சரிபார்ப்பு தேவை.',
    addProduct: 'பொருள் சேர்',
    editProductTitle: 'பொருள் திருத்து',
    addNewProduct: 'புதிய பொருள் சேர்',
    addProductByVoice: 'குரலில் பொருள் சேர்க்கவும்',
    voiceAddHintAdd: 'சேர்: "தக்காளி 10கி 50ரூ"',
    voiceAddHintQuantity: 'அளவு புதுப்பிப்பு: "தக்காளி 20கி" (கையிருப்பில் சேர்க்கும்)',
    voiceAddHintPrice: 'விலை புதுப்பிப்பு: விலை புதுப்பிப்பு பகுதியில் செய்யவும்',
    startSpeaking: 'பேச தொடங்கு',
    stopListening: 'கேட்பதை நிறுத்து',
    youSaid: 'நீங்கள் சொன்னது:',
    productNameLabel: 'பொருள் பெயர்',
    productNamePlaceholder: 'பொருள் பெயர்',
    brandLabel: 'பிராண்ட்',
    brandPlaceholder: 'பிராண்ட் பெயர் (விருப்பம்)',
    priceLabel: 'விலை (ரூ.)',
    quantityLabel: 'அளவு',
    expiryDateLabel: 'காலாவதி தேதி',
    expiryDateHelp: 'எச்சரிக்கைக்காக காலாவதி தேதியை அமைக்கவும் (விருப்பம்)',
    expiryDateValue: 'காலாவதி தேதி: {{date}}',
    synonymsLabel: 'மாற்றுப் பெயர்கள்',
    synonymsPlaceholder: 'எ.கா., தயிர், டஹி, யோகுர்ட் (கமாவால் பிரிக்கவும்)',
    synonymsHelp: 'விவித பெயர்களில் பேசும்போது கண்டுபிடிக்க மாற்றுப் பெயர்கள் சேர்க்கவும்',
    saving: 'சேமிக்கிறது...',
    updateProduct: 'பொருள் புதுப்பி',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    reportsLoadFailed: 'அறிக்கைகளை ஏற்ற முடியவில்லை',
    reportsTitle: 'விற்பனை அறிக்கைகள்',
    reportsSubtitle: 'தினம், மாதம், ஆண்டு அடிப்படையில் கண்காணிக்கவும்.',
    breakdownByPeriod: '{{period}} வாரியான பகிர்வு',
    periodLabel: 'காலம்',
    salesLabel: 'விற்பனை',
    billsLabel: 'பில்கள்',
    itemsSoldLabel: 'விற்பனையான பொருட்கள்',
    avgBillLabel: 'சராசரி பில்',
    noReportData: 'இந்த காலத்திற்கு தரவு இல்லை.',
    productReportTitle: 'பொருள் விற்பனை',
    productReportSubtitle: 'ஒரு பொருளின் விற்பனையை பார்க்கவும்.',
    selectProduct: 'பொருள் தேர்வு',
    loadingProductReport: 'பொருள் அறிக்கை ஏற்றுகிறது...',
    loadingReports: 'அறிக்கைகள் ஏற்றுகிறது...',
    selectProductHint: 'ஒரு பொருளை தேர்வு செய்யவும்.',
    totalSales: 'மொத்த விற்பனை',
    avgPriceLabel: 'சராசரி விலை',
    daily: 'தினசரி',
    monthly: 'மாதாந்திர',
    yearly: 'வருடாந்திர',
    priceUpdate: 'விலை புதுப்பிப்பு',
    priceUpdateDesc: 'குரலின் மூலம் விலைகளை புதுப்பிக்கவும்.',
    priceUpdateAction: 'விலையை புதுப்பி',
    priceUpdateTitle: 'குரல் விலை புதுப்பிப்பு',
    priceUpdateVoiceTitle: 'குரலில் விலை புதுப்பிப்பு',
    priceUpdateHint: '"அரிசி விலை 50" அல்லது "சர்க்கரை விலை 42" என்று சொல்லுங்கள்.',
    priceUpdateNotDetected: 'சரியான விலை புதுப்பிப்பு கண்டுபிடிக்கப்படவில்லை.',
    priceUpdateInvalid: 'தவறான விலை கண்டுபிடிக்கப்பட்டது.',
    priceUpdateDetected: '{{name}} → ரூ.{{price}} கண்டுபிடிக்கப்பட்டது',
    priceUpdateFailed: 'விலை புதுப்பிப்பு தோல்வி.',
    priceUpdatedSuccess: '✓ {{name}} விலை ரூ.{{price}} ஆக புதுப்பிக்கப்பட்டது',
    priceUpdateDetectedTitle: 'விலை புதுப்பிப்பை உறுதி செய்யவும்',
    currentPriceLabel: 'தற்போதைய விலை',
    applyPriceUpdate: 'உறுதிசெய்து புதுப்பி',
    pinHint: '4 இலக்க PIN ஐ உள்ளிடவும்',
    enterShopIdError: 'உங்கள் கடை ID ஐ உள்ளிடவும்',
    fillAllFields: 'அனைத்து புலங்களையும் நிரப்பவும்',
    fillRequiredFields: 'அனைத்து தேவையான புலங்களையும் நிரப்பவும்',
    registerShopFailed: 'கடை பதிவு தோல்வி',
    registerShopkeeperFailed: 'கடைக்காரர் பதிவு தோல்வி',
    registering: 'பதிவு செய்கிறது...',
    selectYourName: 'உங்கள் பெயரை தேர்வு செய்யவும்',
    multipleShopkeepersFound: 'பல கடைக்காரர்கள் உள்ளனர். உங்கள் பெயரை தேர்வு செய்யவும்.',
    print: 'அச்சிடு',
    shareViaWhatsapp: 'WhatsApp மூலம் பகிர்'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language')
    return saved || 'en'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const t = (key, vars = {}) => {
    const template = translations[language][key] || key
    return template.replace(/\{\{(\w+)\}\}/g, (_, token) => (
      vars[token] !== undefined ? vars[token] : ''
    ))
  }

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ta' : 'en')
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
